### ISSUE TITLE
Les pays doivent être crées manuellement à l'installation

### ISSUE THREAD

**Issue by clemlatz** [biblys/biblys#1]
## Problème

Aujourd'hui, les pays sont enregistrés en base de données, dans la table `countries`. La table est utilisée à différents endroits, par exemple [pour afficher à l'utilisateur une liste de pays lors de l'enregistrement d'une commande](https://github.com/clemlatz/biblys/blob/64849115325229f0f4005790d9a4ec326d60f561/controllers/common/php/cart.php#L368). Le pays choisi par l'utilisateur est ensuite enregistré, lorsque la commande est validée, dans la colonne `country_id` de la table `orders`. 

Enregistrer les pays en base de données a peu d'intérêt, car ce sont des données qui changent très rarement et qui seront identiques sur toutes instance de Biblys. De plus, cela oblige à remplir la table à l'installation, ce qui aujourd'hui doit être fait manuellement.

## Proposition de solution

Mettre les pays en dur dans le code, par exemple dans un repository, avec des méthodes `getById` et `getAll` (au moins) qui retournerait des objets `Country`. 

Export de la table en prod : [countries.csv](https://github.com/user-attachments/files/15787170/countries.csv)

## Notes

- Idéalement, il faudrait utiliser les codes ISO comme identifiant unique, mais dans un premier temps, pour assurer la rétro-compatibilité, il faut garder la colonne `country_id`
- Le même transfert de la base de données au code a été fait pour [les types d'articles](https://github.com/clemlatz/biblys/blob/1597bf3a734ddef9dada413240c103fc560afa4b/src/Biblys/Article/Type.php#L7) et les [rôles des contributeurs](https://github.com/clemlatz/biblys/blob/1597bf3a734ddef9dada413240c103fc560afa4b/src/Biblys/Contributor/Job.php) qui étaient autrefois aussi dans la base.

**Comment by HEYGUL** [comment]
@clemlatz on pourrait également garder ces données de référence en base de données et résoudre le problème du remplissage manuel avec une migration remplissant les données de références.
